### PR TITLE
Add AsyncTcpTransport integration tests

### PR DESCRIPTION
**Pull request by abrown**
@jefft0 I re-factored the example and brought it in to the integration tests because it now runs very quickly; we can leave it as an example but the JUnit library has a lot of helpful methods for verifying that it works. For me it ran with `mvn clean verify -P with-integration-tests` (one side note: `TestFaceInterestMethods.testNetworkNack` seemed to fail).

### CODE REVIEW

**Comment by andrewsbrown** [comment]
@weiyu2001 can you test this out as well?

**Comment by weiyu2001** [comment]
all tests seem to pass

**Comment by jefft0** [comment]
`mvn verify -P with-integration-tests` fails for me with the output below.

    Running src.net.named_data.jndn.tests.integration_tests.TestAsyncTcpTransport
    Jun 16, 2016 8:55:35 AM src.net.named_data.jndn.tests.integration_tests.TestAsyncTcpTransport testHappyPath
    INFO: testHappyPath()
    Jun 16, 2016 8:55:35 AM src.net.named_data.jndn.tests.integration_tests.TestAsyncTcpTransport$MockNfd start
    INFO: Started mock NFD
    Jun 16, 2016 8:55:35 AM src.net.named_data.jndn.tests.integration_tests.TestAsyncTcpTransport$MockNfdReader <init>
    INFO: New mock NFD connection
    Jun 16, 2016 8:55:35 AM src.net.named_data.jndn.tests.integration_tests.TestAsyncTcpTransport$MockNfdReader start
    INFO: Started mock NFD connection
    Jun 16, 2016 8:55:35 AM src.net.named_data.jndn.tests.integration_tests.TestAsyncTcpTransport sendPacket
    INFO: Sending: happy path
    Jun 16, 2016 8:55:35 AM src.net.named_data.jndn.tests.integration_tests.TestAsyncTcpTransport$MockNfdReader run
    INFO: Received new packet: happy path
    Jun 16, 2016 8:55:35 AM src.net.named_data.jndn.tests.integration_tests.TestAsyncTcpTransport$MockNfd stop
    INFO: Stopping mock NFD...
    Jun 16, 2016 8:55:35 AM src.net.named_data.jndn.tests.integration_tests.TestAsyncTcpTransport$MockNfdReader close
    INFO: Closing mock NFD connection
    Jun 16, 2016 8:55:35 AM src.net.named_data.jndn.tests.integration_tests.TestAsyncTcpTransport testWithoutServerInitiallyOn
    INFO: testWithoutServerInitiallyOn()
    Jun 16, 2016 8:55:35 AM src.net.named_data.jndn.tests.integration_tests.TestAsyncTcpTransport sendPacket
    INFO: Sending: not up initially
    Jun 16, 2016 8:55:35 AM src.net.named_data.jndn.tests.integration_tests.TestAsyncTcpTransport$MockNfd start
    INFO: Started mock NFD
    Jun 16, 2016 8:55:35 AM src.net.named_data.jndn.tests.integration_tests.TestAsyncTcpTransport sendPacket
    INFO: Sending: not up initially
    Jun 16, 2016 8:55:35 AM src.net.named_data.jndn.tests.integration_tests.TestAsyncTcpTransport sendPacket
    INFO: Sending: not up initially
    Jun 16, 2016 8:55:35 AM src.net.named_data.jndn.tests.integration_tests.TestAsyncTcpTransport$MockNfdReader <init>
    INFO: New mock NFD connection
    Jun 16, 2016 8:55:35 AM src.net.named_data.jndn.tests.integration_tests.TestAsyncTcpTransport$MockNfdReader start
    INFO: Started mock NFD connection
    Jun 16, 2016 8:55:35 AM src.net.named_data.jndn.tests.integration_tests.TestAsyncTcpTransport sendPacket
    INFO: Sending: not up initially
    Jun 16, 2016 8:55:35 AM src.net.named_data.jndn.tests.integration_tests.TestAsyncTcpTransport$MockNfdReader run
    INFO: Received new packet: not up initially
    Jun 16, 2016 8:55:35 AM src.net.named_data.jndn.tests.integration_tests.TestAsyncTcpTransport$MockNfd stop
    INFO: Stopping mock NFD...
    Jun 16, 2016 8:55:35 AM src.net.named_data.jndn.tests.integration_tests.TestAsyncTcpTransport$MockNfdReader close
    INFO: Closing mock NFD connection
    Jun 16, 2016 8:55:35 AM src.net.named_data.jndn.tests.integration_tests.TestAsyncTcpTransport$MockNfd start
    INFO: Started mock NFD
    Jun 16, 2016 8:55:35 AM src.net.named_data.jndn.tests.integration_tests.TestAsyncTcpTransport$MockNfdReader <init>
    INFO: New mock NFD connection
    Jun 16, 2016 8:55:35 AM src.net.named_data.jndn.tests.integration_tests.TestAsyncTcpTransport$MockNfd stop
    INFO: Stopping mock NFD...
    Jun 16, 2016 8:55:35 AM src.net.named_data.jndn.tests.integration_tests.TestAsyncTcpTransport$MockNfdReader start
    INFO: Started mock NFD connection
    Jun 16, 2016 8:55:35 AM src.net.named_data.jndn.tests.integration_tests.TestAsyncTcpTransport$MockNfd start
    INFO: Started mock NFD
    Jun 16, 2016 8:55:35 AM src.net.named_data.jndn.tests.integration_tests.TestAsyncTcpTransport sendPacket
    INFO: Sending: nfd reboot
    Jun 16, 2016 8:55:35 AM src.net.named_data.jndn.tests.integration_tests.TestAsyncTcpTransport$MockNfdReader run
    INFO: Received new packet: nfd reboot
    Jun 16, 2016 8:55:35 AM src.net.named_data.jndn.tests.integration_tests.TestAsyncTcpTransport$MockNfd stop
    INFO: Stopping mock NFD...
    Jun 16, 2016 8:55:35 AM src.net.named_data.jndn.tests.integration_tests.TestAsyncTcpTransport$MockNfdReader close
    INFO: Closing mock NFD connection
    Jun 16, 2016 8:55:35 AM src.net.named_data.jndn.tests.integration_tests.TestAsyncTcpTransport$MockNfd start
    INFO: Started mock NFD
    Jun 16, 2016 8:55:35 AM src.net.named_data.jndn.tests.integration_tests.TestAsyncTcpTransport$MockNfdReader <init>
    INFO: New mock NFD connection
    Jun 16, 2016 8:55:35 AM src.net.named_data.jndn.tests.integration_tests.TestAsyncTcpTransport$MockNfd stop
    INFO: Stopping mock NFD...
    Jun 16, 2016 8:55:35 AM src.net.named_data.jndn.tests.integration_tests.TestAsyncTcpTransport$MockNfdReader start
    INFO: Started mock NFD connection
    Jun 16, 2016 8:55:36 AM src.net.named_data.jndn.tests.integration_tests.TestAsyncTcpTransport sendPacket
    INFO: Sending: reboot while idling
    Jun 16, 2016 8:55:36 AM src.net.named_data.jndn.tests.integration_tests.TestAsyncTcpTransport$MockNfdReader run
    INFO: Received new packet: reboot while idling
    Jun 16, 2016 8:55:36 AM src.net.named_data.jndn.tests.integration_tests.TestAsyncTcpTransport$MockNfd stop
    INFO: Stopping mock NFD...
    Jun 16, 2016 8:55:36 AM src.net.named_data.jndn.tests.integration_tests.TestAsyncTcpTransport$MockNfdReader close
    INFO: Closing mock NFD connection
    Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.365 sec <<< FAILURE! - in src.net.named_data.jndn.tests.integration_tests.TestAsyncTcpTransport
    testWithServerRebootWhileIdling(src.net.named_data.jndn.tests.integration_tests.TestAsyncTcpTransport)  Time elapsed: 0.212 sec  <<< FAILURE!
    java.lang.AssertionError: expected:<0> but was:<1>
      at org.junit.Assert.fail(Assert.java:93)
      at org.junit.Assert.failNotEquals(Assert.java:647)
      at org.junit.Assert.assertEquals(Assert.java:128)
      at org.junit.Assert.assertEquals(Assert.java:472)
      at org.junit.Assert.assertEquals(Assert.java:456)
      at src.net.named_data.jndn.tests.integration_tests.TestAsyncTcpTransport.testWithServerRebootWhileIdling(TestAsyncTcpTransport.java:161)

**Comment by andrewsbrown** [comment]
Ok, I'll take a look at this.

**Comment by jefft0** [comment]
Hi @abrown, this pull request is pretty out of date. Can we close it?

**Comment by abrown** [comment]
Absolutely 😄. Looks like I forgot to follow up on this... for three years.

**Pull request closed without merging**
